### PR TITLE
Add a index.yaml file

### PR DESCRIPTION
**Pull request by jyx11011**

### CODE REVIEW

**Review by limli — DISMISSED** [review]

**Review by SuyashLakhotia — APPROVED** [review]

**Review by SuyashLakhotia — CHANGES_REQUESTED** [review]
Is a more appropriate place for this with the rest of the backend Java code? Instead of with the frontend code here?

**Comment by jyx11011** [comment]
The document https://cloud.google.com/datastore/docs/tools/indexconfig#Datastore_About_index_yaml says the file should be in WEB-INF folder.

**Comment by SuyashLakhotia** [comment]
Ack, does the "Refactor restaurant generator" commit belong to this PR? Feels like that should be a separate change and this should only focus on `index.yaml`?

**Comment by jyx11011** [comment]
Sorry, I mistakenly pushed that to this branch. It belongs to #113. I will remove this commit.

**Review by SuyashLakhotia — APPROVED** [review]

**Pull request merged**
