### PR TITLE
Add comment sentiment attribute to comment

### PR DESCRIPTION
**Pull request by lisasgoh**
Screenshot 2020-07-28 at 6 11 30 PM

It only works when I deploy it, so I showed the scores on the comments to show its working.

### CODE REVIEW

**Comment by limli** [comment]
what are you going to use the sentiment for at the end?

**Comment by lisasgoh** [comment]
> what are you going to use the sentiment for at the end?
Getting the trending deals probably

**Comment by limli** [comment]
> Getting the trending deals probably

Maybe don't need to show the sentiment score in the boxes of the comment, because this shouldn't show up in the actual UI. Whatever merged into master might get deployed, so try to keep master clean. We can verify the scores by checking the datastore, since you saved it there.

**Comment by lisasgoh** [comment]
> > Getting the trending deals probably
> 
> Maybe don't need to show the sentiment score in the boxes of the comment, because this shouldn't show up in the actual UI. Whatever merged into master might get deployed, so try to keep master clean. We can verify the scores by checking the datastore, since you saved it there.

Its not in this PR, I just did it to show the screenshot

**Comment by limli** [comment]
> Its not in this PR, I just did it to show the screenshot

Oh ok I see

**Review by anuragshirolkar — DISMISSED** [review]

**Review by anuragshirolkar — DISMISSED** [review]

**Review by anuragshirolkar — APPROVED** [review]

**Pull request merged**
